# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-1809@sha256:0819cadea58b154086b3377f8ad94aed7da47f2afb7f56c582474d416d6d0f10
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
