# escape=`
FROM mcr.microsoft.com/powershell:nanoserver-2004@sha256:2c1bfed1f30a7170ac71fe08900261b87f6df9a5ed41cec6838c307a8c948259
USER ContainerAdministrator

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Base" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
